DEVICE          : cuda              # device used for training and evaluation (cpu, cuda, cuda0, cuda1, ...)
SAVE_DIR        : '/media/ailab/HDD1/Workspace/src/Project/Drone24/detection/drone-MemorySAM/outputs' #AblationStudy_frozen_memorymechanism'          # output folder name used for saving the model, logs and inference results

MODEL:
  NAME          : CMNeXt                                            # name of the model you are using
  BACKBONE      : CMNeXt-B2                                         # model variant
  PRETRAINED    : '/media/ailab/HDD1/Workspace/src/Project/Drone24/detection/drone-mmdetection-jm/pretrained_weights/segformer/mit_b2.pth'     # backbone model's weight 
  RESUME        : ''                                                # checkpoint file 

DATASET:
  NAME          : DELIVER                                       # dataset name to be trained with (camvid, cityscapes, ade20k)
  ROOT          : '/media/ailab/HDD1/Workspace/src/Project/Drone24/detection/drone-MemorySAM/data/DELIVER'                                   # dataset root path
  IGNORE_LABEL  : 255 
  # MODALS        : ['img']
  # MODALS        : ['depth']
  # MODALS        : ['img', 'depth']
  # MODALS        : ['img', 'event']
  # MODALS        : ['img', 'lidar']
  # MODALS        : ['img', 'depth', 'event']
  # MODALS        : ['img', 'depth', 'lidar']
  MODALS        : ['img', 'depth']

TRAIN:
  IMAGE_SIZE    : [1024, 1024]    # training image size in (h, w)
  BATCH_SIZE    : 2         # batch size used to train
  EPOCHS        : 200             # number of epochs to train
  EVAL_START    : 0             # evaluation interval start
  EVAL_INTERVAL : 1               # evaluation interval during training
  AMP           : false           # use AMP in training
  DDP           : True            # use DDP training

LOSS:
  NAME          : OhemCrossEntropy          # loss function name 
  CLS_WEIGHTS   : false            # use class weights in loss calculation

OPTIMIZER:
  NAME          : adamw           # optimizer name
  LR            : 0.0006         # initial learning rate used in optimizer
  WEIGHT_DECAY  : 0.01            # decay rate used in optimizer

SCHEDULER:
  NAME          : warmuppolylr    # scheduler name
  POWER         : 0.9             # scheduler power
  WARMUP        : 10              # warmup epochs used in scheduler
  WARMUP_RATIO  : 0.1             # warmup ratio
  

EVAL:
  # MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgb.pth'
  # MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgbd.pth'
  # MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgbe.pth'
  # MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgbl.pth'
  # MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgbde.pth'
  # MODEL_PATH    : 'output/DELIVER/cmnext_b2_deliver_rgbdl.pth'
  MODEL_PATH    : '/hpc2hdd/home/cliao127/MMSS-SAM-Logs/Main/AblationStudy_RGBD_mo08_weight1lr0.00045/DELIVER_CMNeXt-B2_id/epoch154_63.48.pth'
  IMAGE_SIZE    : [1024, 1024]                            # evaluation image size in (h, w)        
  BATCH_SIZE    : 5      
  MSF: 
    ENABLE      : false                                   # multi-scale and flip evaluation  
    FLIP        : true                                    # use flip in evaluation  
    SCALES      : [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]       # scales used in MSF evaluation                


TEST:
  MODEL_PATH    : ''    # trained model file path
  FILE          : '/hpc2hdd/home/cliao127/SAMDELIVER/data/DELIVER'                          # filename or foldername 
  IMAGE_SIZE    : [1024, 1024]                            # inference image size in (h, w)
  OVERLAY       : false                                   # save the overlay result (image_alpha+label_alpha)
